barcodes_pricingrules_index:
    path:     /
    defaults: { _controller: "BarcodesAppBundle:Pricingrule:index" }
    methods:  GET

barcodes_pricingrules_indexnew:
    path:     /indexnew
    defaults: { _controller: "BarcodesAppBundle:Pricingrule:index" }
    methods:  GET

barcodes_pricingrules_show:
    path:     /{id}/show
    defaults: { _controller: "BarcodesAppBundle:Pricingrule:show" }
    methods:  GET

barcodes_pricingrules_new:
    path:     /new
    defaults: { _controller: "BarcodesAppBundle:Pricingrule:new" }
    methods:  [GET, POST]

barcodes_pricingrules_edit:
    path:     /{id}/edit
    defaults: { _controller: "BarcodesAppBundle:Pricingrule:edit" }
    methods:  [GET, POST]

barcodes_pricingrules_delete:
    path:     /{id}/delete
    defaults: { _controller: "BarcodesAppBundle:Pricingrule:delete" }
    methods:  DELETE
