Barcodes\Bundle\AppBundle\Entity\Pricingrule:
    type: entity
    table: barcodes_pricingrules
    repositoryClass: Barcodes\Bundle\AppBundle\Repository\PricingruleRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        manufacturer:
            type: string
            length: '255'
            nullable: true
        category:
            type: string
            length: '255'
            nullable: true
        product:
            type: string
            length: '255'
            nullable: true
        pricetype:
            type: string
            length: '255'
        operator:
            type: string
            length: '10'
        value:
            type: integer
        channel:
            type: string
            length: '255'
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                    on: update
                    on: create
    lifecycleCallbacks: {  }
