<?php

namespace Barcodes\Bundle\AppBundle\Repository;

/**
 * PricingruleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PricingruleRepository extends \Doctrine\ORM\EntityRepository
{
}
